### ISSUE TITLE
download course issue 

### ISSUE THREAD

**Issue by djoudi** [muhamed-didovic/ccdown#10]
ccdown https://codecourse.com/courses/learn-livewire -e myemail  -p  mypassword  -d learn-livewire  -v yes

/usr/local/lib/node_modules/ccdown/lib/cli.js:2
import meow from "meow";
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by djoudi** [comment]
@muhamed-didovic

**Comment by muhamed-didovic** [comment]
@djoudi I pushed something, please verify, also which version of nodejs do you use?
